# Generated by Django 5.1.5 on 2025-05-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_delete_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
