services:
  - type: web
    name: payments-api
    env: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn payments_api.wsgi:application
    postDeployCommand: python manage.py collectstatic --noinput
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: payments_api.settings
      - key: PYTHON_VERSION
        value: 3.12
